### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iptvsmartws** [Krowemoh/vlc.js#1]
getting error : 

experimental.js:268 requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag
(anonyme) @ experimental.js:268
experimental.js:272 Uncaught (in promise) Error: bad memory
    at experimental.js:272:31
    at VLCPlayer (vlc.js:10:27)
    at window.onload (vlc/:45:15)

**Comment by hugorezende** [comment]
You need to set in the server side
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```
